"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[aws]
symbol = "  "
disabled = true

[azure]
format = 'on [$symbol($subscription)]($style) '
disabled = true

[gcloud]
disabled = true

[directory]
read_only = " 󰌾"
truncate_to_repo = true

[docker_context]
symbol = " "
disabled = true

[git_branch]
symbol = " "

[git_commit]
tag_symbol = '  '

[golang]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "
disabled = true

[os.symbols]
Amazon = " "
Android = " "
Arch = " "
CentOS = " "
Debian = " "
Garuda = "󰛓 "
Kali = " "
Linux = " "
Macos = " "
Mint = " "
NixOS = " "
openSUSE = " "
OracleLinux = "󰌷 "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
SUSE = " "
Ubuntu = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "

[gradle]
symbol = " "
disabled = true

[kubernetes]
disabled = false
detect_extensions = ['kubectl','oc','kubectx','kubens']
#format = '[$symbol($user in)()](bold blue)'
#symbol = '☸  '

